// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int edgecase = Integer.parseInt(args[0]);
		int greaterthanhalf = 0;
		int lessthanorequalhalf = 0;
		
		for (int i = 0; i < edgecase; i++) 
		{
			double random = Math.random();

			if (random > 0.5) {
				greaterthanhalf++;
			}  
			else { 
				lessthanorequalhalf++;
			}
		}
		
		System.out.println("> 0.5: " + greaterthanhalf + " times");
		System.out.println( "<= 0.5: " + lessthanorequalhalf + " times");

			
			if (lessthanorequalhalf ==0) {
				System.out.println("invalid Ratio, Numerator=0");
				} 
			else {
					double ratio = (double) greaterthanhalf / lessthanorequalhalf;
					System.out.println( "ratio: " + ratio);
				} 
	   }
}
